import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        vintage: {
          dark: "#213555",
          medium: "#3E5879",
          light: "#D8C4B6",
          lightest: "#F5EFE7",
        },
        sepia: {
          50: "#fcf9f5",
          100: "#f6efe3",
          200: "#ebdbc3",
          300: "#ddbd96",
          400: "#cd9e6a",
          500: "#bd8243",
          600: "#a86a36",
          700: "#8a522f",
          800: "#71432c",
          900: "#5e3828",
          950: "#331b12",
        },
        olive: {
          50: "#f8f9f2",
          100: "#eef0e2",
          200: "#d9dfc5",
          300: "#bcc8a0",
          400: "#9bae76",
          500: "#7d9353",
          600: "#617743",
          700: "#4c5d37",
          800: "#404c30",
          900: "#364029",
          950: "#1c2315",
        },
        sage: {
          50: "#f6f7f6",
          100: "#e3e6e3",
          200: "#c5ccc5",
          300: "#a1ada1",
          400: "#7e8c7e",
          500: "#637363",
          600: "#4d5b4d",
          700: "#3e483e",
          800: "#343c34",
          900: "#2c322c",
          950: "#171b17",
        },
        coral: {
          50: "#fef2f2",
          100: "#ffe1e1",
          200: "#ffcaca",
          300: "#fe9e9e",
          400: "#fc6464",
          500: "#f73e3e",
          600: "#e51a1a",
          700: "#c11414",
          800: "#a01414",
          900: "#841717",
          950: "#480707",
        },
        sand: {
          50: "#fbf9f2",
          100: "#f5f0e0",
          200: "#ebe0c0",
          300: "#decb96",
          400: "#d0b26b",
          500: "#c49c4d",
          600: "#b7873d",
          700: "#976c33",
          800: "#7a572f",
          900: "#654a29",
          950: "#372615",
        },
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        satoshi: ["Satoshi", "sans-serif"],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "slide-up": {
          from: { transform: "translateY(10px)", opacity: "0" },
          to: { transform: "translateY(0)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "slide-up": "slide-up 0.5s ease-out",
      },
      backdropFilter: {
        'none': 'none',
        'blur': 'blur(8px)',
      },
      boxShadow: {
        'glass': '0 4px 30px rgba(0, 0, 0, 0.1)',
        'neobrutal': '4px 4px 0px #000000',
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
