// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nbkfhipyojaosyeyuofi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ia2ZoaXB5b2phb3N5ZXl1b2ZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3NzA3NzgsImV4cCI6MjA1OTM0Njc3OH0.gYlrf9AF1q5Vye9-rFFcVA_rVnU5EMFgXTziSvrIkxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);